# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release

addons:
  apt:
    packages:
      - libudunits2-dev
      - libmagick++-dev

# for pkgdown
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - travis_wait Rscript -e 'covr::codecov()'
