// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_greedy_search
List run_greedy_search(List nbr_idx, NumericVector z_vec, NumericVector sc_means, NumericVector sc_stds, CharacterVector node_names, int max_depth, int search_depth, int n_nodes, double overlap_threshold, int subnetwork_num);
RcppExport SEXP _pathfindR_run_greedy_search(SEXP nbr_idxSEXP, SEXP z_vecSEXP, SEXP sc_meansSEXP, SEXP sc_stdsSEXP, SEXP node_namesSEXP, SEXP max_depthSEXP, SEXP search_depthSEXP, SEXP n_nodesSEXP, SEXP overlap_thresholdSEXP, SEXP subnetwork_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nbr_idx(nbr_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_vec(z_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc_means(sc_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc_stds(sc_stdsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type node_names(node_namesSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type search_depth(search_depthSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< double >::type overlap_threshold(overlap_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type subnetwork_num(subnetwork_numSEXP);
    rcpp_result_gen = Rcpp::wrap(run_greedy_search(nbr_idx, z_vec, sc_means, sc_stds, node_names, max_depth, search_depth, n_nodes, overlap_threshold, subnetwork_num));
    return rcpp_result_gen;
END_RCPP
}
// java_node_order
CharacterVector java_node_order(CharacterVector src, CharacterVector tgt);
RcppExport SEXP _pathfindR_java_node_order(SEXP srcSEXP, SEXP tgtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type tgt(tgtSEXP);
    rcpp_result_gen = Rcpp::wrap(java_node_order(src, tgt));
    return rcpp_result_gen;
END_RCPP
}
// java_neighbour_order
IntegerVector java_neighbour_order(IntegerVector nbr_insertion_ids, CharacterVector nbr_insertion_names);
RcppExport SEXP _pathfindR_java_neighbour_order(SEXP nbr_insertion_idsSEXP, SEXP nbr_insertion_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type nbr_insertion_ids(nbr_insertion_idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nbr_insertion_names(nbr_insertion_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(java_neighbour_order(nbr_insertion_ids, nbr_insertion_names));
    return rcpp_result_gen;
END_RCPP
}
// get_java_zscores
NumericVector get_java_zscores(NumericVector pvals);
RcppExport SEXP _pathfindR_get_java_zscores(SEXP pvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvals(pvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(get_java_zscores(pvals));
    return rcpp_result_gen;
END_RCPP
}
// get_java_mc_calibration
List get_java_mc_calibration(NumericVector z_scores, int trials, int seed);
RcppExport SEXP _pathfindR_get_java_mc_calibration(SEXP z_scoresSEXP, SEXP trialsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z_scores(z_scoresSEXP);
    Rcpp::traits::input_parameter< int >::type trials(trialsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_java_mc_calibration(z_scores, trials, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pathfindR_run_greedy_search", (DL_FUNC) &_pathfindR_run_greedy_search, 10},
    {"_pathfindR_java_node_order", (DL_FUNC) &_pathfindR_java_node_order, 2},
    {"_pathfindR_java_neighbour_order", (DL_FUNC) &_pathfindR_java_neighbour_order, 2},
    {"_pathfindR_get_java_zscores", (DL_FUNC) &_pathfindR_get_java_zscores, 1},
    {"_pathfindR_get_java_mc_calibration", (DL_FUNC) &_pathfindR_get_java_mc_calibration, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pathfindR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
