// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_greedy_search_cpp
List run_greedy_search_cpp(List nbr_idx, NumericVector z_vec, NumericVector sc_means, NumericVector sc_stds, int max_depth, int search_depth, int n_nodes);
RcppExport SEXP _pathfindR_run_greedy_search_cpp(SEXP nbr_idxSEXP, SEXP z_vecSEXP, SEXP sc_meansSEXP, SEXP sc_stdsSEXP, SEXP max_depthSEXP, SEXP search_depthSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nbr_idx(nbr_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_vec(z_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc_means(sc_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc_stds(sc_stdsSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type search_depth(search_depthSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(run_greedy_search_cpp(nbr_idx, z_vec, sc_means, sc_stds, max_depth, search_depth, n_nodes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pathfindR_run_greedy_search_cpp", (DL_FUNC) &_pathfindR_run_greedy_search_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_pathfindR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
