# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_greedy_search_cpp <- function(nbr_idx, z_vec, sc_means, sc_stds, max_depth, search_depth, n_nodes) {
    .Call(`_pathfindR_run_greedy_search_cpp`, nbr_idx, z_vec, sc_means, sc_stds, max_depth, search_depth, n_nodes)
}

