# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_greedy_search <- function(nbr_idx, z_vec, sc_means, sc_stds, node_names, max_depth, search_depth, n_nodes, overlap_threshold, subnetwork_num) {
    .Call(`_pathfindR_run_greedy_search`, nbr_idx, z_vec, sc_means, sc_stds, node_names, max_depth, search_depth, n_nodes, overlap_threshold, subnetwork_num)
}

java_node_order <- function(src, tgt) {
    .Call(`_pathfindR_java_node_order`, src, tgt)
}

java_neighbour_order <- function(nbr_insertion_ids, nbr_insertion_names) {
    .Call(`_pathfindR_java_neighbour_order`, nbr_insertion_ids, nbr_insertion_names)
}

get_java_zscores <- function(pvals) {
    .Call(`_pathfindR_get_java_zscores`, pvals)
}

get_java_mc_calibration <- function(z_scores, trials = 2000L, seed = 1234L) {
    .Call(`_pathfindR_get_java_mc_calibration`, z_scores, trials, seed)
}

run_simulated_annealing <- function(csr_offsets, csr_nbrs, z, means, stds, n_nodes, gene_init_prob, start_with_all_positives, sa_initial_temp, sa_final_temp, sa_iterations, seed) {
    .Call(`_pathfindR_run_simulated_annealing`, csr_offsets, csr_nbrs, z, means, stds, n_nodes, gene_init_prob, start_with_all_positives, sa_initial_temp, sa_final_temp, sa_iterations, seed)
}

component_scores_sorted <- function(on, csr_offsets, csr_nbrs, z, means, stds) {
    .Call(`_pathfindR_component_scores_sorted`, on, csr_offsets, csr_nbrs, z, means, stds)
}

