# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_greedy_search <- function(nbr_idx, z_vec, sc_means, sc_stds, node_names, max_depth, search_depth, n_nodes, overlap_threshold, subnetwork_num, seed) {
    .Call(`_pathfindR_run_greedy_search`, nbr_idx, z_vec, sc_means, sc_stds, node_names, max_depth, search_depth, n_nodes, overlap_threshold, subnetwork_num, seed)
}

get_java_zscores <- function(pvals) {
    .Call(`_pathfindR_get_java_zscores`, pvals)
}

get_java_mc_calibration <- function(z_scores, trials = 2000L, seed = 42L) {
    .Call(`_pathfindR_get_java_mc_calibration`, z_scores, trials, seed)
}

